To php8
umbrellio/jaravel pull request #3
Opened 2021-07-20 16:55 UTC by sgnatyuk

Пришлось обновить пакет jukylin/jaeger-php шоб заработало на php8:
https://github.com/jukylin/jaeger-php/pull/101#issuecomment-821015823

2021-08-19 12:16 UTC, lazeevv requested changes

2021-08-23 11:28 UTC, sgnatyuk commented on src/config/jaravel.php
> +
поправил

2021-08-30 13:36 UTC, lazeevv requested changes

2021-08-30 13:36 UTC, lazeevv commented on src/JaravelServiceProvider.php
> +                'logging' => true,
это избыточное логирование, кажется

2021-08-30 13:36 UTC, lazeevv commented on src/Services/Span/SpanCreator.php
> +        $spanContext = $this->tracer->extract(Formats\TEXT_MAP, ['x-trace-id' => $traceIdHeader]);
всегда x-trace-id?

2021-08-31 16:10 UTC, merged